# Generated by Django 5.1.5 on 2025-02-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['unique_code', 'name'], 'verbose_name_plural': 'Membership'},
        ),
    ]
